/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.entity.Usuario;
import br.ulbra.dao.UsuarioDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.gt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */
public class FrCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrCadastro
     */
    public FrCadastro() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null); //coloca o formulário no centro da tela 
        ControlarBtn(1);
        EdIdCad1.setEnabled(false);
        readJTable();
        BtBuscarCEP.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EdPesquisar = new javax.swing.JTextField();
        BtPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        BtNovoCad = new javax.swing.JButton();
        PnCad = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        BtAlterar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        EdCepCad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        EdLograCad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        EdEmailCadastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtBuscarCEP = new javax.swing.JButton();
        EdSenha1 = new javax.swing.JPasswordField();
        EdSenha2 = new javax.swing.JPasswordField();
        EdTel = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        EdIdCad1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        EdNomeCad = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        EdNumCad = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        EdBairroCad = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        EdCidadeCad = new javax.swing.JTextField();
        RbMasc = new javax.swing.JRadioButton();
        RbFem = new javax.swing.JRadioButton();
        RbAlt = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        EdEstadoCad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE USUÁRIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 450, -1, 0));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pesquisar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        EdPesquisar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(EdPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 56, 410, 19));

        BtPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        BtPesquisar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/cadastro_search_icon.png"))); // NOI18N
        BtPesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 28, -1));

        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD", "NOME", "CEP", "LOGRADOURO", "Nº", "BAIRRO", "CIDADE", "ESTADO", "E-MAIL", "TELEFONE", "SEXO", "SENHA"
            }
        ));
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 600, 76));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/bala.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        BtNovoCad.setBackground(new java.awt.Color(255, 255, 255));
        BtNovoCad.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtNovoCad.setText("Novo Cadastro");
        BtNovoCad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        BtNovoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoCadActionPerformed(evt);
            }
        });
        jPanel1.add(BtNovoCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 600, -1));

        PnCad.setBackground(new java.awt.Color(102, 102, 102));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Opções");

        BtAlterar.setBackground(new java.awt.Color(255, 255, 255));
        BtAlterar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtSalvar.setBackground(new java.awt.Color(255, 255, 255));
        BtSalvar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtExcluir.setBackground(new java.awt.Color(255, 255, 255));
        BtExcluir.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Logra.");

        EdCepCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdCepCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdCepCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdCepCadActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nome");

        EdLograCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdLograCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdLograCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdLograCadActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("E-mail");

        EdEmailCadastro.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdEmailCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdEmailCadastroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Confirme");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo");

        BtBuscarCEP.setBackground(new java.awt.Color(255, 255, 255));
        BtBuscarCEP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtBuscarCEP.setText("Buscar CEP");
        BtBuscarCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        BtBuscarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarCEPActionPerformed(evt);
            }
        });

        EdSenha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        EdSenha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        EdTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 102)));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID");

        EdIdCad1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdIdCad1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdIdCad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdIdCad1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CEP");

        EdNomeCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdNomeCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdNomeCadActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nº");

        EdNumCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdNumCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdNumCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdNumCadActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Bairro");

        EdBairroCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdBairroCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdBairroCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdBairroCadActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cidade");

        EdCidadeCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdCidadeCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdCidadeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdCidadeCadActionPerformed(evt);
            }
        });

        RbMasc.setBackground(new java.awt.Color(255, 0, 51));
        buttonGroup1.add(RbMasc);
        RbMasc.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        RbMasc.setForeground(new java.awt.Color(255, 255, 255));
        RbMasc.setText("Masculino");
        RbMasc.setBorderPainted(true);
        RbMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbMascActionPerformed(evt);
            }
        });

        RbFem.setBackground(new java.awt.Color(255, 0, 51));
        buttonGroup1.add(RbFem);
        RbFem.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        RbFem.setForeground(new java.awt.Color(255, 255, 255));
        RbFem.setText("Feminino");
        RbFem.setBorderPainted(true);
        RbFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbFemActionPerformed(evt);
            }
        });

        RbAlt.setBackground(new java.awt.Color(255, 0, 51));
        buttonGroup1.add(RbAlt);
        RbAlt.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        RbAlt.setForeground(new java.awt.Color(255, 255, 255));
        RbAlt.setText("Outro");
        RbAlt.setBorderPainted(true);
        RbAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAltActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Estado");

        EdEstadoCad.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EdEstadoCad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        EdEstadoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdEstadoCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnCadLayout = new javax.swing.GroupLayout(PnCad);
        PnCad.setLayout(PnCadLayout);
        PnCadLayout.setHorizontalGroup(
            PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnCadLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(EdIdCad1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnCadLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EdBairroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnCadLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EdLograCad, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnCadLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EdCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnCadLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EdEstadoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnCadLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EdEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnCadLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel8))
                            .addGroup(PnCadLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdNumCad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RbFem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RbAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EdCepCad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtBuscarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdTel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        PnCadLayout.setVerticalGroup(
            PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(EdIdCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(EdNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(EdCepCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscarCEP))
                .addGap(18, 18, 18)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdLograCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(EdNumCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(EdBairroCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(RbMasc)
                        .addGap(9, 9, 9)
                        .addComponent(RbFem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbAlt))
                    .addGroup(PnCadLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(EdCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(EdEstadoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(EdEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(EdSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(EdSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EdTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(PnCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtSalvar)
                        .addComponent(BtAlterar)
                        .addComponent(BtExcluir)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel1.add(PnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 530, 470));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/img/bala.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtBuscarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarCEPActionPerformed
    }//GEN-LAST:event_BtBuscarCEPActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed

        Usuario u = new Usuario();

        try {
            UsuarioDAO ud = new UsuarioDAO();
            u.setIdUsu(Integer.parseInt(EdIdCad1.getText()));
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Excluir?", "Confirme exclusão", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                ud.delete(u);
                readJTable();
                ControlarBtn(1);
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada!");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }

    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed

        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();
            u.setNomeUsu(EdNomeCad.getText());
            u.setCepUsu(EdCepCad.getText());
            u.setLogUsu(EdLograCad.getText());
            u.setNumUsu(Integer.parseInt(EdNumCad.getText()));
            u.setBairroUsu(EdBairroCad.getText());
            u.setCidadeUsu(EdCidadeCad.getText());
            u.setEstadoUsu(EdEstadoCad.getText());
            u.setEmailUsu(EdEmailCadastro.getText());
            u.setSenhaUsu(EdSenha1.getText());
            u.setTelUsu(EdTel.getText());
            if (RbMasc.isSelected()) {
                u.setSexoUsu(1);
            } else if (RbFem.isSelected()) {
                u.setSexoUsu(2);
            } else {
                u.setSexoUsu(3);
            }
            if (EdSenha1.getText().equals(EdSenha2.getText())) {
                u.setIdUsu(Integer.parseInt(EdIdCad1.getText()));
                ud.update(u);
                readJTable();
                ControlarBtn(1);
            } else {
                JOptionPane.showMessageDialog(null, "Você inseriu senhas diferentes!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(FrCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtAlterarActionPerformed

    private void RbAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbAltActionPerformed

    private void RbFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbFemActionPerformed

    private void RbMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbMascActionPerformed

    private void EdEmailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdEmailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdEmailCadastroActionPerformed

    private void EdLograCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdLograCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdLograCadActionPerformed

    private void BtNovoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoCadActionPerformed
        ControlarBtn(2);

    }//GEN-LAST:event_BtNovoCadActionPerformed

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        ControlarBtn(3);
        if (tbUsuario.getSelectedRow() != -1) {
            EdIdCad1.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0).toString());
            EdNomeCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 1).toString());
            EdCepCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 2).toString());
            EdLograCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 3).toString());
            EdNumCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 4).toString());
            EdBairroCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 5).toString());
            EdCidadeCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 6).toString());
            EdEstadoCad.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 7).toString());
            EdEmailCadastro.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 8).toString());
            EdTel.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 9).toString());
            int s = (int) tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 10);
            if (s == 1) {
                RbMasc.setSelected(true);
            } else if (s == 2) {
                RbFem.setSelected(true);
            } else {
                RbAlt.setSelected(true);
            }

            EdSenha1.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 11).toString());
            EdSenha2.setText(EdSenha1.getText());
        }
    }//GEN-LAST:event_tbUsuarioMouseClicked

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        try {
            readJTableForDesc(EdPesquisar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FrCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void EdPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdPesquisarActionPerformed

    private void EdNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdNomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdNomeCadActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        ControlarBtn(1);
        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();
            u.setNomeUsu(EdNomeCad.getText());
            u.setCepUsu(EdCepCad.getText());
            u.setLogUsu(EdLograCad.getText());
            u.setNumUsu(Integer.parseInt(EdNumCad.getText()));
            u.setBairroUsu(EdBairroCad.getText());
            u.setCidadeUsu(EdCidadeCad.getText());
            u.setEstadoUsu(EdEstadoCad.getText());
            u.setEmailUsu(EdEmailCadastro.getText());
            u.setTelUsu(EdTel.getText());
            u.setSenhaUsu(EdSenha1.getText());

            if (RbMasc.isSelected()) {
                u.setSexoUsu(1);
            } else if (RbFem.isSelected()) {
                u.setSexoUsu(2);
            } else {
                u.setSexoUsu(3);
            }

            if (EdSenha1.getText().equals(EdSenha2.getText())) {
                ud.create(u);
                readJTable();
            } else {
                JOptionPane.showMessageDialog(null, "As senhas estão diferentes!");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void EdNumCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdNumCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdNumCadActionPerformed

    private void EdBairroCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdBairroCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdBairroCadActionPerformed

    private void EdCidadeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdCidadeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdCidadeCadActionPerformed

    private void EdEstadoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdEstadoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdEstadoCadActionPerformed

    private void EdIdCad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdIdCad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdIdCad1ActionPerformed

    private void EdCepCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdCepCadActionPerformed
        ControlarBtn(1);
    }//GEN-LAST:event_EdCepCadActionPerformed

    public void ControlarBtn(int op) {
        switch (op) {
            case 1:
                PnCad.setVisible(false);
                BtSalvar.setEnabled(true);
                break;

            case 2:
                PnCad.setVisible(true);
                BtSalvar.setEnabled(true);
                BtAlterar.setEnabled(false);
                BtExcluir.setEnabled(false);
                break;

            case 3:
                PnCad.setVisible(true);
                BtAlterar.setEnabled(true);
                BtExcluir.setEnabled(true);
                BtSalvar.setEnabled(false);
                break;
        }
        this.pack();

    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();
        for (Usuario p : udao.read()) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCepUsu(),
                p.getLogUsu(),
                p.getNumUsu(),
                p.getBairroUsu(),
                p.getCidadeUsu(),
                p.getEstadoUsu(),
                p.getEmailUsu(),
                p.getTelUsu(),
                p.getSexoUsu(),
                p.getSenhaUsu()
            });
        }
    }

    public void readJTableForDesc(String nome) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO pdao = new UsuarioDAO();
        for (Usuario p : pdao.readForDesc(nome)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getCepUsu(),
                p.getLogUsu(),
                p.getNumUsu(),
                p.getBairroUsu(),
                p.getCidadeUsu(),
                p.getEstadoUsu(),
                p.getEmailUsu(),
                p.getTelUsu(),
                p.getSexoUsu(),
                p.getSenhaUsu()
            });
        }
    }

    public void buscarCep(String cep) {
        String json;
        try {
            URL url = new URL("http://viacep.com.br/ws/" + cep + "/json");
            URLConnection urlConnection = url.eopenConnection();
            InputStream is = urlConnection.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            StringBuilder jsonSb = new StringBuilder();
            br.lines().forEach(l -> jsonSb.append(l.trim()));
            json = jsonSb.toString();
            JOptionPane.showMessageDialog(null, json);
            json = json.replaceAll( "[{},:]","");
json = json.replaceAll("\"", "\n");
            String array[] = new String[30];
            array = json.split("\n");
            JOptionPane.showMessageDialog(null, array);
            String logradouro = array[7];
            String bairro = array[15];
            String cidade = array[19];
            String uf = array[23];
            EdLograCad.setText(logradouro);
            EdBairroCad.setText(bairro);
            EdCidadeCad.setText(cidade);
            EdEstadoCad.setText(uf);
            JOptionPane.showMessageDialog(null, logradouro + " " + bairro + " "
                    + cidade + " " + uf);
        } catch (Exception e) {
            throw new RuntimeException(e);
            JOptionPane.showMessageDialog(null, "Erro" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrCadastro().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(FrCadastro.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtBuscarCEP;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovoCad;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField EdBairroCad;
    private javax.swing.JTextField EdCepCad;
    private javax.swing.JTextField EdCidadeCad;
    private javax.swing.JTextField EdEmailCadastro;
    private javax.swing.JTextField EdEstadoCad;
    private javax.swing.JTextField EdIdCad1;
    private javax.swing.JTextField EdLograCad;
    private javax.swing.JTextField EdNomeCad;
    private javax.swing.JTextField EdNumCad;
    private javax.swing.JTextField EdPesquisar;
    private javax.swing.JPasswordField EdSenha1;
    private javax.swing.JPasswordField EdSenha2;
    private javax.swing.JTextField EdTel;
    private javax.swing.JPanel PnCad;
    private javax.swing.JRadioButton RbAlt;
    private javax.swing.JRadioButton RbFem;
    private javax.swing.JRadioButton RbMasc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsuario;
    // End of variables declaration//GEN-END:variables
}
